services:
  - type: web
    name: barbarella-app
    env: python
    buildCommand: |
      python manage.py collectstatic --noinput
    startCommand: gunicorn barbarella_project.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: DJANGO_SECRET_KEY
        value: 'django-insecure-o(05a$@%2^2xjm+8cnd$ct9c26)4)&*(=6u4serg-7xr0oy!j'
      - key: DEBUG
        value: "False"
      - key: PORT
        value: "10000"